### ISSUE TITLE
Switch from-to controls to range slider where applicable

### ISSUE THREAD

**Issue by jhrcek** [RoboZonky/natural-strategy-setup#10]
Use [range slider](http://package.elm-lang.org/packages/enetsee/rangeslider/1.0.0/RangeSlider) control for setting investment sizes and portfolio shares. This should also make it possible to get rid of form validation by hardwiring valid values into the slider settings (min= 200, max = 5000) and ensure that min is always less than max.

**Comment by jhrcek** [comment]
@triceo I tried using a range slider library and to enable configuring [Struktura portfolia](http://janhrcek.cz/natural-strategy-setup/) using that. The library has some bugs (e.g. when you drag min & max to same value you can't change it anymore) related to Drag & Drop.

Let me know what you think about this implementation. Do you consider it user friendlier?
If you like it I'll use the sliders in "Výše investice" as well.

**Comment by triceo** [comment]
What's supposed to be wrong with it? :-) Worked fairly smoothly on my Chrome.

**Comment by jhrcek** [comment]
At least one edge case reported in the [range-slider's issues](https://github.com/stephenreddek/elm-range-slider/issues/5). Also I encountered some non-deterministic drag and drop behavior when Drag and dropping one "knob" multiple times in a row.

**Comment by jhrcek** [comment]
@triceo Loosely related to range sliders in Struktura portfoklia I was thinking how to visualize portfolio structure better than with a table and I tried using elm-plot (because it was easy - just [3 lines of code](https://github.com/RoboZonky/natural-strategy-setup/blob/0f76853713d8a1298591307046b4d75162a290b7/src/View/PortfolioStructure.elm#L65-L67) AND I like the library). WDYT? Should I incorporate it there or not?

**Comment by jhrcek** [comment]
Now both portfolio structure and Investment sizes are configured using range sliders. This made the validation in these sections no longer necessary, as valid values are "hardwired" in the range slider components. https://github.com/RoboZonky/natural-strategy-setup/commit/f57291ba586013c8e200a8444e113a4104a94e19
