### ISSUE TITLE
Print code version

### ISSUE THREAD

**Issue by triceo** [RoboZonky/natural-strategy-setup#11]
The website should show some version identifier, which it should also write into the strategy file. This will help when debugging problems with strategies generated by users.

**Comment by jhrcek** [comment]
I added github commit hash (--short) to the generated strategy file and link to github commit to the page footer. See it [in action](http://janhrcek.cz/natural-strategy-setup/). Are you ok with this solution?

The deployed version also contains basic filter creation functionality (at the moment only supporting setting positive conditions). I'm not happy with the visual side, but function-wise it works as I imagined. Let's discuss it tomorrow (or note it down to our shared doc).

**Comment by jhrcek** [comment]
Translate to czech, add link for reporting issues.

**Comment by jhrcek** [comment]
Translated to czech and added link to github issues: https://github.com/RoboZonky/natural-strategy-setup/commit/628aa45ee8770184043f6c021d50af20aabd89db
