### ISSUE TITLE
Switching minimum balance doesn't do anything

### ISSUE THREAD

**Issue by triceo** [RoboZonky/natural-strategy-setup#14]
When clicking on "Investovat pouze pokud disponibilní zůstatek přesáhne ...", nothing happens to the strategy on the right, until I change the field value to be something else than 200.

I think that this is a bug. RoboZonky behavior of 200 and "undefined" will be slightly different.

**Comment by jhrcek** [comment]
It was intended behaviour. I was intentionally not adding the value to the strategy if it was equal to default. Anyway I changed it as you requested & redeployed. Similar behaviour is implemented in "Výše investice" accordion section. Should I change it there as well (to always show strategy values even when equal to defaults?)

**Comment by triceo** [comment]
We should probably change it there as well.

- "Undefined" means that it's 1 CZK for secondary marketplace and 200 CZK for primary marketplace.
- While "200" will set a minimum to 200 for both primary and secondary marketplace.

**Comment by jhrcek** [comment]
Also needs to be changed for "Disponibilní zůstatek"

**Comment by jhrcek** [comment]
All mentioned values are now rendered in the strategy config even when equal to defaults.
