### ISSUE TITLE
Visualize investment shares by pie charts

### ISSUE THREAD

**Issue by jhrcek** [RoboZonky/natural-strategy-setup#19]
Align pie slices colors with rating colors from https://zonky.cz/otazky-a-odpovedi-investor

**Comment by jhrcek** [comment]
@triceo I was just thinking: How do we visualize share maximums if they add up to more than 100%? Just normalize them to add to 100% by dividing each by the total sum of maximums, so that they add to 100%. What does it even  mean if you set all maximums e.g. to 100%

**Comment by triceo** [comment]
Setting maximums to 100 % across the board will mean that every loan will be invested as it appears on the marketplace. Therefore it is impossible to determine what the portfolio structure will be. In practice, this means that the portfolio will be heavily biased towards A+ and better, as these are the most frequent ratings. But it is impossible to guarantee. 

I see two options:

- Normalizing.
- Not showing the pie chart for the maximums. At least the form would be easier to understand.

**Comment by jhrcek** [comment]
I implemented experimental pie chart visualization. I tried making it as close to what's in Zonky FAQ. See it in action http://janhrcek.cz/natural-strategy-setup/ 
The only thing I don't like is how the labels overlap when you set percentage for some rating too close to 0, but not sure how to make it better. Maybe displaying chart legend next to the chart kind of [like this](https://i.stack.imgur.com/yE1gx.png)? Wdyt?

**Comment by triceo** [comment]
Yep, displaying the legend next to the chart seems like the way to go.

**Comment by jhrcek** [comment]
@triceo 2nd attempt implemented. Check it and let me know what you think about the legend next to the chart.

**Comment by triceo** [comment]
Looks good, I like it!

**Comment by jhrcek** [comment]
Enhancement implemented in https://github.com/RoboZonky/natural-strategy-setup/commit/566657f6579feeaa2ad34fef796af90d656e5ae1
