### ISSUE TITLE
Downloaded strategy - follow same format as default Robozonky file

### ISSUE THREAD

**Issue by Marfusios** [RoboZonky/natural-strategy-setup#29]
Hello,

it would be great if the downloaded strategy follows default format - `robozonky-strategy.cfg` (instead of `strategy.txt`) and UTF-8 encoding (already does). 

See issue it has indirectly caused: [181](https://github.com/RoboZonky/robozonky/issues/181)

**Comment by jhrcek** [comment]
Hello,

If I understand it right, the only change you're requesting is changing the name of strategy file that's downloaded, right? I fixed that here https://github.com/RoboZonky/natural-strategy-setup/commit/2f283d29496c9eab4d826a14805368249629d0d0 but will deploy the change to the website only after you confirm that that's what you wanted.

Also, just ouf of curiosity, could you please be more specific and explain how it (indirectly) caused the mentioned issue in robozonky?

**Comment by jhrcek** [comment]
@Marfusios thanks for the explanation. The config tool is now using the same filename as expected by Robozonky, so no renaming should be necessary from now on.
