### ISSUE TITLE
Style the app using bootstrap

### ISSUE THREAD

**Issue by jhrcek** [RoboZonky/natural-strategy-setup#3]
Use accordions to make the form less formidable by only allowing 1 section expanded at any given time.

**Comment by jhrcek** [comment]
Basic bootstrap styling (accordion and filter creation modal) implemented. The inner accordion subforms still need to be migrated to bootstrap.

**Comment by triceo** [comment]
![snimek z 2017-08-29 07-52-04](https://user-images.githubusercontent.com/247403/29806360-2dc034d8-8c8f-11e7-93dd-cdc8ae4fedc8.png)

Not sure if it has something to do with your last comment, but there seems to be a glitch in rendering the tables inside the accordions.

**Comment by jhrcek** [comment]
@triceo Don't worry, styling of inner forms is still in progress (at the moment it's still just plain html)
