### ISSUE TITLE
Strategy now much less permissive

### ISSUE THREAD

**Issue by triceo** [RoboZonky/natural-strategy-setup#31]
As a result of https://github.com/RoboZonky/robozonky/issues/169, the following changes were made to the strategy for _RoboZonky 4.3.0_, and need to be implemented in the web tool:

* The `- Filtrování tržiště` section, if included, must now include at least one filter.
    - Primary marketplace filters can be ommitted if, instead, `Ignorovat všechny půjčky.` or `Investovat do všech půjček.` is included.
    - Secondary marketplace filters can be ommitted if, instead, `Ignorovat všechny participace.` or `Investovat do všech participací.` is included.
* Not including the above section is only allowed if either one of the following lines is included instead:
    - `Ignorovat primární i sekundární tržiště.`
    - `Investovat do všech půjček a participací.`
* Not including the `- Prodej participací` header is only allowed if the `Prodej participací zakázán.` line is included instead.
    - If the header is included, however, it must be followed by at least one sell rule.

These changes have been made in order to make the strategy more explicit and to not confuse users. It becomes obvious which parts of the robot are disabled and what the behavior of the robot is in any given situation.

None of these rules are actually enforced (yet). Old strategies will work as they used to, but the parser will log warnings. _RoboZonky 4.4.0_ will start enforcing these and the parser will fail where it logged warnings before.

Let me know if anything needs more discussion.

**Comment by triceo** [comment]
Oh, and I forgot to mention that none of the above applies to the "one-line" strategy. `Robot má udržovat ...` will still work as it used to.

**Comment by triceo** [comment]
All relevant commits are referenced here:
https://github.com/RoboZonky/robozonky/issues/169

**Comment by jhrcek** [comment]
Ok, I'll think about best way to support that and not to complicate the UI too much

> Oh, and I forgot to mention that none of the above applies to the "one-line" strategy

Some time ago we decided not to support one-line strategies in the web tool. Would you agree that I can keep ignoring those? Anyone who wants to use them can still write the one-liner by hand, leaving the web tool simpler and focusing on more complex strategies..

**Comment by jhrcek** [comment]
Note for self: look at FilteredItem enum and look if it can be simplified after these changes.

**Comment by triceo** [comment]
Wrt. https://github.com/RoboZonky/natural-strategy-setup/issues/31#issuecomment-354772075: I agree.

**Comment by jhrcek** [comment]
@triceo I'm studying the antlr grammar changes and there's also new "Opustit Zonky k" feature. Do you want me to implement support for that as well? Which would be the best section to put it (probably Obecna nastaveni ?)

**Comment by triceo** [comment]
@jhrcek Good point, forgot about that. Yes, that will need to be implemented too.

Not sure how to implement it best. One option would be to, when this option is enabled, disable almost every other option. :-) But that would have to be thought through in big detail to make sure options that still make sense can still be enabled.

**Comment by jhrcek** [comment]
@triceo ok, I'll handle that separately (https://github.com/RoboZonky/natural-strategy-setup/issues/32) and will focus on this one first.

**Comment by jhrcek** [comment]
TODOs after discussion with @triceo 
1. In strategy parser change "Ignorovat primární i sekundární tržiště." to "Ignorovat všechny půjčky a participace." to make it consistent with the rest of the grammar.

2. enforce at most one of "Ignorovat všechny půjčky." checkboxes to be checked "Ignorovat všechny participace."

**Comment by jhrcek** [comment]
@triceo all of the changes were implemented. In particular
1. You can only select at most one of "Ignorovat všechny půjčky." and "Ignorovat všechny participace."
2. Any change in Selling / Buying config that would lead to removal of filters now shows you modal showing which filters will be deleted, giving you the option cancel the change (and not delete any filter).

Please try this in [my deployment](http://janhrcek.cz/natural-strategy-setup/) and let me know if anything needs changing.

**Comment by triceo** [comment]
Very nice! I especially like the modals, which are very informative. (Unlike many other modals of the world. :-))
