### ISSUE TITLE
Add support for "Výstupní strategie"

### ISSUE THREAD

**Issue by jhrcek** [RoboZonky/natural-strategy-setup#32]
As implemented in https://github.com/RoboZonky/robozonky/issues/192

**Comment by jhrcek** [comment]
@triceo I implemented first draft of exit strategy support [here](http://janhrcek.cz/natural-strategy-setup/)
Check it out in section "Obecná nastavení" (same place as you have it in the parser).

I'm unsure about many things, lets clarify when we meet next time:
1. Is it in the most intuitive section of the form?
2. Are the labels for UI controls correct/understandable?
3. I should probably add tooltips to that exit section, but not sure what to put in them (not sure I understand the semantics of the feature right)

**Comment by jhrcek** [comment]
@triceo Feedback incorporated in https://github.com/RoboZonky/natural-strategy-setup/commit/30b4ff2000878d1e624ab95717144527b55e7d74
Please [check it out](http://janhrcek.cz/natural-strategy-setup/) and let me know if any more changes are needed

**Comment by triceo** [comment]
Looks good!

**Comment by jhrcek** [comment]
Changes incorporated in https://github.com/RoboZonky/robozonky/pull/202
