### ISSUE TITLE
Add note about zonkoid

### ISSUE THREAD

**Issue by jhrcek** [RoboZonky/natural-strategy-setup#33]
Add tooltip next to "Potvrzovat mobilem investice do úvěrů s ratingem" informing users that this relies on zonkoid to work. Mode details can be found in [robozonky wiki](https://github.com/RoboZonky/robozonky/wiki/ZASTARAL%C3%89-:::-Integrace-se-Zonkoidem-a-CAPTCHA#co-m%C3%ADt-na-pam%C4%9Bti)

**Comment by jhrcek** [comment]
@triceo I added tooltip with text "Tato funkce vyžaduje instalaci mobilní aplikace Zonkoid, kterou si můžete stáhnout na zonkoid.cz". Are you ok with the text? I intentionally didn't make this into link, as the tooltip is only shown when hovering over the question mark icon and would disappear after moving mouse into the tooltip. You can check it out [here](http://janhrcek.cz/natural-strategy-setup/).

**Comment by triceo** [comment]
Looks good!
