### ISSUE TITLE
Implement possibility to save / load strategy config for later editing

### ISSUE THREAD

**Issue by jhrcek** [RoboZonky/natural-strategy-setup#35]
TODO find out if it's possible to process file "upload" via client side only.

**Comment by jhrcek** [comment]
@triceo I've got some [rough implementation](http://janhrcek.cz/natural-strategy-setup/) of saving / restoring state using local storage and it works nice in chrome and firefox (for now ignore the placement, missing tooltips, missing confirmation dialogs etc). "Obnovit strategii" button appears after you save and refresh the page. Let me dump some thoughts / worries for later discussion.


I can think of three major ways to persist the state of the tool's form (supposing we want to keep things simple and remain client-side only):

### 1. Local storage
The tool would have a bunch of buttons for managing saving / loading of the form state.
- "Uložit" button with tooltip "Uloží stav formuláře v paměti prohlížeče.Při příští návštěvě na této strance ze stejného počítače můžete uloženou konfiguraci obnovit".
    - will be disabled (but visible) when strategy invalid
- "Obnovit" button in case previously saved strategy was found in local storage
    - will be hidden when nothing previously saved
* Advantages
    - easy to work with, just clicking buttons
* Disadvantages
    - it will be confusing if user moves to different PC which won't have the saved data in local storage.
    - won't be available if user's browser doesn't support local storage (should not happen with [modern browsers](https://caniuse.com/#feat=namevalue-storage))


### 2. Downloadable file with form state
There would be two buttons
- "Stáhnout (TODO how to call it)"
- "Nahrát (TODO how to call it)"

* Disadvantage
    - it might be confusing that users will be able to download two types of files from the tool (1. config for robozonky and 2. form state "config")
    - TODO I'd have to figure out if "uploading" file is possible without server. It seems to be [possible](https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications) but would require me to write more javascript :P Alternatively users would have to "paste" the content of the file into some input field.
* Advantage
    - location independent - if you have the file, you can restore the strategy from it

### 3. Shareable URL
- Provide a "Share" button, which would open an input field from which users would copy a (longish) URL with strategy state encoded into json and obfuscated (to prevent modifications).

* Advantage: just paste url to restore the state, just one button. User would have to copy & paste the generated url and save it in some file manually ..
* Disadvantage - the URL will be relatively long (rougly like the plaintext of strategy config)

**Comment by triceo** [comment]
@jhrcek I think I like 3 the most - it seems to be the simplest and universally accessible. The URL to the strategy could be put to the strategy itself as a comment, so people needn't remember it or write it down. Also, the strategy URL probably wouldn't be extremely long if we chose to encode it with something like Base64. (But yes, it will still be long.)

One thing we need to solve is the versioning business - how do we tell which migrations to apply to a strategy file to move it to the latest version supported by the tool?

**Comment by triceo** [comment]
(For future reference: https://rfc.zeromq.org/spec:32/Z85/ is essentially "Base85" for even more space efficiency.)

**Comment by jhrcek** [comment]
The more I think about it, the more I like option 3 too. Also I like your idea of putting the comment with URL to strategy config itself :+1: I'll try this approach next and see where it gets me.

Regarding strategy versioning and future changes of format: I'll simply provide a function for migration of each new version of strategy like [this](https://github.com/RoboZonky/natural-strategy-setup/blob/strategyPersistence/src/Data/Strategy/Persistence.elm#L51-L58)

**Comment by jhrcek** [comment]
I looked at Base85 and it doesn't seem to be suitable for putting into URL (there are only [73 valid characters](https://stackoverflow.com/questions/1278934/shortest-encoding-for-guid-for-use-in-a-url#answer-1278988) that can be put into URL without escaping). But let's worry about space efficiency later, after I've got first working implementation :-)

**Comment by jhrcek** [comment]
@triceo [here](http://janhrcek.cz/natural-strategy-setup/) is a rough sketch of form state serialized in URL. More work is required (appropriate error reporting when deserialization from URL fails, expand the text area so the config preview fits etc.), but the core logic is there. The url is sometimes veery long. Also for some reason it doesn't work when I put the comment with url at the end (getting some exceptions from robozonky parser) so for now I put the comment with url in the beginning. Check it out and let's discuss it tomorrow.

**Comment by jhrcek** [comment]
Note for self: [lz-string](http://pieroxy.net/blog/pages/lz-string/index.html) compresses the encoded strategy to about 1/3 length.

**Comment by triceo** [comment]
Looks good! I'll see what I can do about the parser.

**Comment by triceo** [comment]
@jhrcek Comments at the end of the file work. Tried it. In fact, there's no reason why they wouldn't - whatever is detected as a comment, it gets disregarded by the parser. Do you have an example of a strategy that doesn't work?

**Comment by jhrcek** [comment]
> Comments at the end of the file work

Indeed, you're right. I looked at the parser and noticed that the comment line HAS to end with a newline, which I didn't have the last time. So I moved the strategy comment to the end and redeployed. Let's discuss tomorrow if it's ready for deployment.

**Comment by jhrcek** [comment]
@triceo I think I'm satisfied with the current implementation, you can check it out [here](http://janhrcek.cz/natural-strategy-setup/) and if you like it I'll create PR to official robozonky site.

Changes from last time
- I finished migration to bootstrap 4
- added a bunch of tests
- added alerts for both successful renewal of strategy from url as well as when renewal from URL fails (in that case I show a link to github issue which pre-fills invalid url data + error what went wrong)

**Comment by triceo** [comment]
LGTM @jhrcek.

**Comment by jhrcek** [comment]
Ok, created PR to robozonky repo https://github.com/RoboZonky/robozonky/pull/223
