### ISSUE TITLE
Importování strategie pomocí URL nefunguje

### ISSUE THREAD

**Issue by Betonar** [RoboZonky/natural-strategy-setup#44]
Přestože se zobrazí hláška, že načtení bylo úspěšné, tak strategie načtená není.

**Comment by triceo** [comment]
Pošlete log, prosím - bez toho nemám šanci zjistit, co se stalo.
(Sám mám strategii z URL a funguje mi to.)

**Comment by jhrcek** [comment]
Prosím ideálně přidejte URL (celou adresu, ze ktere se strategii snažíte obnovit), případně celý konfigurační soubor `robozonky-strategy.cfg`

**Comment by jhrcek** [comment]
Zavírám issue, protože uživatel neposkytl požadované detaily.
