### ISSUE TITLE
People still don't understand filters

### ISSUE THREAD

**Issue by triceo** [RoboZonky/natural-strategy-setup#47]
After a summer break in questions from people who have gotten filtering entirely wrong, they are now properly back. Apparently the changes we've made didn't help. Let's go for "the nuclear option." Here's what I propose:

- When a rule is first created, the UI **does not allow** people to add a second condition.
- When the rule is re-opened, additional conditions can be added.

This way, users will have to spend **extra energy** to shoot themselves in the foot, instead of shooting themselves in the foot by default. WDYT @jhrcek ?

**Comment by jhrcek** [comment]
@triceo Shouldn't be that hard to implement. Let's discuss the details in person.

**Comment by jhrcek** [comment]
@triceo I deployed the latest improvements (https://github.com/RoboZonky/natural-strategy-setup/issues/49 and https://github.com/RoboZonky/natural-strategy-setup/issues/48) to my [testing deployment](https://janhrcek.cz/natural-strategy-setup/). Also restructured the [filter documentation](https://github.com/RoboZonky/natural-strategy-setup/blob/master/docs/BuySellConfig.md) some more. Please check it out and let me know if ok and I'll create PR to robozonky.github.io

**Comment by triceo** [comment]
@jhrcek Sieht gut aus. Danke vielmals!
