### ISSUE TITLE
Migrate to Elm 0.19

### ISSUE THREAD

**Issue by jhrcek** [RoboZonky/natural-strategy-setup#51]

**Comment by jhrcek** [comment]
@triceo I managed to migrate everything to Elm 0.19.
As part of that I had to replace some dependencies, hopefully not breaking anything (did automated and manual testing). You might want to do some sanity testing in my [testing deployment](https://janhrcek.cz/natural-strategy-setup/) and let me know if you find some issue.

Apart from staying up to date with latest developments and brutally improved compile times (the whole project now compiles in ~1 second), the only observable difference this upgrade brings is smaller size of the generated javascript (from 312KB to 157KB (49KB gzipped)), which should mean slightly faster loading time :smile: 

Now I'm going to start working on the latest strategy changes and will create PR to robozonky.github.io when ready.

**Comment by triceo** [comment]
@jhrcek OK, I'll retest this when the new strategy changes are implemented. That way, I test the final product.
