### ISSUE TITLE
Add support for participation sale without fees

### ISSUE THREAD

**Issue by triceo** [RoboZonky/natural-strategy-setup#58]
See https://github.com/RoboZonky/robozonky/issues/400 which adds a new sale filter.

**Comment by triceo** [comment]
(Will be available in RoboZonky 5.2.0.CR1, to be released today. The final most likely 2 weeks later.)

**Comment by triceo** [comment]
I described all the changes here: https://github.com/RoboZonky/robozonky/wiki/Co-nov%C3%A9ho-ve-verzi-5.2

**Comment by jhrcek** [comment]
Ok, I'll work on this in the next few days

**Comment by jhrcek** [comment]
@triceo I checked the changes.
This will require changes in "Pravidla prodeje" section.
Until now, there were 2 states represented implicitly:
1. Prodej participací zakázán. (represented by no sell rules being added)
2. Prodej participací povolen (represented by 1+ sell rules being added)

This change will require third state to be added
3. Prodávat všechny participace bez poplatku, které odpovídají filtrům tržiště.

So now we'll have to represent the 3 choices explicitly, probably using 3 radio buttons. Are you ok with this layout (just a mockup so far) or do you have some other proposals?

![Screenshot from 2019-05-02 06-37-27](https://user-images.githubusercontent.com/2716069/57056765-d83fb180-6ca4-11e9-9c7c-e7b4ddd301bf.png)

This will also mean
- validation error will be displayed if 3rd option is selected and no rule is added
- warning modal about rules being removed will be displayed if user has 3rd option selected and 1+ rules and tries to switch to options 1 or 2

**Comment by triceo** [comment]
Makes sense, it is consistent with what we're doing in other places of the tool.

Just one comment, since you didn't mention it - the buttons for adding rules should either be completely gone or at least greyed out when in the first two modes.

**Comment by jhrcek** [comment]
Sure, I'll make it so that the rule-adding buttons are only present when the third option is selected.
