### ISSUE TITLE
Adjust default value for "Výše investice"

### ISSUE THREAD

**Issue by triceo** [RoboZonky/natural-strategy-setup#59]
The current default is "200", meaning that nothing will ever be invested in the secondary marketplace, as this setting means "exactly 200."

I believe that, instead, the default should be "0 to 200" so that we don't lead users down the wrong path. It also makes it more immediately clear that there are actually two buttons there and the user can move both.

**Comment by jhrcek** [comment]
@triceo ok, I can adjust the default minimum. Related to that there's also this [related validation for Target balance](https://github.com/RoboZonky/natural-strategy-setup/blob/master/src/Data/TargetBalance.elm#L30-L37). Would you say that given this lower default it would make sense to remove that validation?

**Comment by jhrcek** [comment]
There's also a question about what do do when restoring older strategies (where 200-200 will be stored). Should I keep restoring them as 200-200 or as 0-200?

**Comment by triceo** [comment]
@jhrcek Wrt. validation of target balance, I agree - in this context, that warning no longer makes sense.

When it comes to existing strategies, I would keep them as is - I think that, for us to change existing strategies, would be an unexpected and surprising behavior.
