### ISSUE TITLE
Clicking on "Nápověda" redirects the window to the documentation with no way to recover ongoing configuration

### ISSUE THREAD

**Issue by mark-stopka** [RoboZonky/natural-strategy-setup#60]
Clicking on "Nápověda" redirects the window to the documentation with no way to recover ongoing configuration; default behaviour should be to open documentation in a new window / tab.

**Comment by jhrcek** [comment]
I agree. I'll implement this. It didn't occur to me, because I always open links like this using click on mouse wheel, to open them in new tab.
