### ISSUE TITLE
Remove support for mobile notifications

### ISSUE THREAD

**Issue by jhrcek** [RoboZonky/natural-strategy-setup#61]
Based on https://github.com/RoboZonky/robozonky/pull/446#issuecomment-517427453

When restoring strategies from URL there should be some kind of warning, like
"Vaše strategie obsahovala nastavení potvrzení investic mobilem. Od RoboZonky verze 5.4.0 tato funkce již nebude podporována, proto bylo toto nastavení odstraněno." (nastavení potvrzení sounds weird, let me know if you come up with better formulation)

**Comment by triceo** [comment]
LGTM. I do not expect there are many users of this functionality.

**Comment by jhrcek** [comment]
Closed via https://github.com/RoboZonky/natural-strategy-setup/pull/62
