### ISSUE TITLE
Remove support for target balance

### ISSUE THREAD

**Issue by jhrcek** [RoboZonky/natural-strategy-setup#63]
https://github.com/RoboZonky/robozonky/pull/448#discussion_r314434337

**Comment by triceo** [comment]
I'm not going to be making any other changes for 5.4. Instead, I'm going to try and release 5.4.0 ASAP, no later than September 15. (The related Zonky changes go into effect on September 14.)

**Comment by jhrcek** [comment]
Ok, so if I understand it right the only thing that needs to be removed from now is "cílová zůstatková částka" in "Obecná nastavení", right? I'll implement the change over the next few days.

**Comment by triceo** [comment]
@jhrcek Correct. Thank you!

**Comment by jhrcek** [comment]
Implemented in https://github.com/RoboZonky/natural-strategy-setup/pull/64
