### ISSUE TITLE
Switching from conservative to user-defined makes it possible to export invalid strategy

### ISSUE THREAD

**Issue by jhrcek** [RoboZonky/natural-strategy-setup#69]
See https://github.com/RoboZonky/robozonky/issues/479

**Comment by jhrcek** [comment]
@triceo fix deployed on my site: https://janhrcek.cz/natural-strategy-setup/

Now floats are supported under the surface meaning:
- switching from conservative (only) to user-defined leaves 0.5 and 1.5 there
- 0.5 and 1.5 are rendered in strategy text
- 0.5 and 1.5 are stored in strategy URL
- 0.5 and 1.5 are restored from URL
- BUT sliders only allow integral precision: once user moves them from those .5 values, he'll only ever be able to set integral values

Demo below:

![FixedIt](https://user-images.githubusercontent.com/2716069/69565220-c90fb080-0fb4-11ea-8359-853441d0bd30.gif)

If ok like this, I'll open PR to robozonky site.

**Comment by triceo** [comment]
The demo looks great, really helpful! :-) Go for it.

**Comment by jhrcek** [comment]
Thanks. It was recorded by [peek](https://github.com/phw/peek) which is amazingly simple tool for recording gifs / screencast videos, should you ever find a use for such thing :) Wholeheartedly recommended. Available in fedora as dnf package `peek`.
