### ISSUE TITLE
5.7.0 overhauls investment strategy

### ISSUE THREAD

**Issue by triceo** [RoboZonky/natural-strategy-setup#70]
Zonky has a new secondary marketplace, which allows to sell problematic loans with a discount, and to purchase these loans from other investors. This unfortunately required strategy format changes in several places.

These changes are described here (in Czech):
https://github.com/RoboZonky/robozonky/wiki/RoboZonky-5.7.0:-Zm%C4%9Bny-ve-strategii

Feel free to edit if you find inconsistencies. For a specific list of changes, I suggest checking strategy source code.

As far as timing is concerned, we are in no hurry. I will probably release a beta soon. Final will be released whenever the web tool has been updated to match.

**Comment by jhrcek** [comment]
Ok, I'll start working on the update over the next few days.

**Comment by jhrcek** [comment]
@triceo I'd like your opinion / preferences regarding the biggest change: splitting of "Výše investice", that was formerly shared by both marketplaces into "Výše investice" (primary) / "Výše nákupu" (secondary). Please either ack or suggest alternative for each point.

1. "Výše investice" will no longer use range sliders, but single value sliders.
2. It will start at 200 Kč and allow steps of 200 Kč up to maximum of 20 000 Kč.
3. When the value 5000 Kč is exceeded, warning will be shown similar to current behavior.
4. "Výše nákupu" - will be added in new separate accordion section, below "Výše investice". 
5. It will also have single value sliders like. What steps size should it use (10/50/100? Using too small value might make it harder to "hit" desired value)?
6. What should be the minimal allowed value on the slider? I'm asking about minimal value of X in the interval (1,X), where 1 is hardcoded in the robot as I understand.
7. What should this section show when "Ignorovat všechny participace" is checked in "Pravidla nákupu"?
     a) all sliders, regardles of "Ignorovat všechny participace" setting  OR
     b) instead of sliders just a message like "Chcete li nakupovat participace na sekundárním tržišti, odškrtněte volbu 'ignorovat všechny participace' v sekci pravidla nákupu".
8. 7.b made me think that similar behavior (hiding the sliders) might be desirable for "Výše investice" too when "Ignorovat všechny půjčky". Should I retrospectively add this behavior too?
Example: it doesn't make much sense to have both of the following in the strategy: "Robot má investovat do úvěrů po 1000 Kč" and "Ignorovat všechny půjčky."

**Comment by triceo** [comment]
Good questions! This took some thinking.

1. Yes.
1. Yes.
1. Yes.
1. Yes.
1. Let's keep it to 200,-.
1. For primary marketplace, I think it needs to be 200. (0 is represented by the line missing.) For secondary marketplace, it should be 1, as that indeed is hardcoded.
1. b)
1. Yes.
1. For primary marketplace, "až 200" means 200. There is nothing less than 200. So the conversion is to the nearest amount divisible by 200, I think. For the secondary marketplace, nothing changes as any number X implicitly means <1, X>.

**Comment by jhrcek** [comment]
Thanks, you answered most of my questions except you may have misunderstood two of them:

6. I understand that minimum of 1 for secondary marketplace is hardcoded in the robot.
The tool should only allow setting upper bound of the interval X.
I was asking about minimum settable value of this upper bound X.
Given that we agreed on 200 as step size, I can easily allow either {0,200,400,...} or {200,400,600,...}
But if you want me to allow values like {1,200,400...}, that would require small hack.
The hardcoded 1 should probably not be mentioned anywhere in the tool (to remain consistent with "Robot má nakupovat participace nejvýše za X" which also doesn't mention the hardcoded 1)

9. So far the tool allowed setting ranges (X to Y) where both X and Y could be only be from {0, 200, 400 ..}
So if user has 2000 - 4000 in the legacy strategy, should I completely discard 2000 and go for 4000 as single value for both primary and secondary marketplace?

**Comment by triceo** [comment]
Ah. 

Wrt. 6 - if you want to hide the 1, I'm fine with that. (The reason for why the 1 is even there is Zonky - sometimes, you get 0.01 Kč participations on the marketplace, and I simply want the robot to ignore those.) So, whether the slider starts with 0 or 200, that's hard to decide. The phrase "Investovat po 0 Kč." makes no sense, so I guess we have to start with 200.

Wrt. 9 - yeah, I think 2000-4000 should simply become 4000. Possibly with a notification.

**Comment by jhrcek** [comment]
@triceo I'm almost done with the implementation, but have one question and 2 issues that are blocking further progress:

1. Issue: parser doesn't accept "- Výše investice" NOT followed by "- Výše nákupu"

Example strategy that fails to parse: https://gist.github.com/jhrcek/244775e4045cfadcbe3440df0cad0c85

I [removed the legacy expressions locally](https://github.com/jhrcek/robozonky/commit/c3181ffbec034a30d32676a63d7bdcc763fa2d71) and made "Výše nákupu" optional to work around this

Can you please modify the parser so it works?

2. Issue: parser fails to parse health condition. By reverse engineering parser I understood that condition like this should be parseable:
"nikdy nebyla, nyní je nebo nyní není po splatnosti"

Sample strategy that fails to parse because of that: https://gist.github.com/jhrcek/0123c84a54836edc6df9736db4db991d

Can you please check if you can parse (e.g. add that to some of your testing strategies)?

3. Question: Is "Zdraví" a good name for the new health condition in conditions dropdown when adding conditions?

**Comment by triceo** [comment]
I'll check on 1 and 2, thanks for reporting.
As to 3, I  think it could also be "HIstorie splácení" or something like that.

**Comment by triceo** [comment]
I have fixed the two problems mentioned. I have also unified some terminology in the strategy. Please see latest updates.

When you're done with the tool, let me know - I'll release Beta 2, so that people can test both the robot and the tool together.

And of course, let me know if there's any other parser issues. Your strategy generator is a miracle. :-)

**Comment by jhrcek** [comment]
Awesome, thank you! I'll finish it today or tomorrow at the latest and let you know.

**Comment by jhrcek** [comment]
@triceo it's ready for testing on https://janhrcek.cz/natural-strategy-setup/
Please test and let me know if you find any issue. I'll open PR for RoboZonky after addressing problems you find (should there be any).

Here's bunch of pictures describing all the visible changes:
1.
![1](https://user-images.githubusercontent.com/2716069/73079763-044f3280-3ec5-11ea-9d6f-ded4834c5679.png)

2.
![2](https://user-images.githubusercontent.com/2716069/73079765-044f3280-3ec5-11ea-8842-ad34c2f5d0a0.png)

3.
![3](https://user-images.githubusercontent.com/2716069/73079767-044f3280-3ec5-11ea-8330-7cf170e3551f.png)

4.
![4](https://user-images.githubusercontent.com/2716069/73079772-04e7c900-3ec5-11ea-8ca5-df22cd93950c.png)

5.
![5](https://user-images.githubusercontent.com/2716069/73079776-05805f80-3ec5-11ea-98fb-897694775392.png)

6.
![6](https://user-images.githubusercontent.com/2716069/73079778-05805f80-3ec5-11ea-9bc4-cabe4c6848ce.png)

7.
![7](https://user-images.githubusercontent.com/2716069/73079781-05805f80-3ec5-11ea-9184-b5259ce101d9.png)

**Comment by triceo** [comment]
@jhrcek I'll be releasing Beta 2 tomorrow, and I'll announce the testing version of this tool as well. Let's see what people find, if anything.

**Comment by jhrcek** [comment]
@triceo so should I do PR to robozonky.github.io? It would be awkward if people had to change the base URL / copy just the hash part to restore their strategies.. I'll just open the PR and let you decide how to release it.

**Comment by triceo** [comment]
Thanks. I won'ŧ be merging just yet, I want existing users to be able to use the existing tool.
It's a beta, a little inconvenience is expected, I think - the current URL will be fine.

**Comment by jhrcek** [comment]
Closing this as the PR https://github.com/RoboZonky/robozonky.github.io/pull/19 was merged
