### ISSUE TITLE
New strategy conditions for 5.9

### ISSUE THREAD

**Issue by triceo** [RoboZonky/natural-strategy-setup#72]
I've made some improvements to the strategy, see https://github.com/RoboZonky/robozonky/commit/d91f71f637070d403fa3507d8471b59a850e7c8d#diff-7c81be9c4de525854322e3899e9f45ad.

I'm not yet sure if the next release will be 5.9 or 6.0. Anyway, these are the only changes to the strategy that I'm planning so far.

Let me know if you have any questions and/or suggestions for improvement.

**Comment by jhrcek** [comment]
Ok, I should be able to implement the new conditions over the next couple of days.

**Comment by triceo** [comment]
I've been thinking... the dropdown for all those conditions is getting quite long, it's hard to find anything in there. Maybe we need a different UX for it? That said, I don't know what that would be. 

Just thinking out loud: Maybe we want to group the conditions by purpose? Loan term, due date, amount, interest rates...

**Comment by jhrcek** [comment]
Ok. I'll first add those conditions and then think about making the UX nicer
