### ISSUE TITLE
New region: Slovensko

### ISSUE THREAD

**Issue by triceo** [RoboZonky/natural-strategy-setup#78]
See https://github.com/RoboZonky/robozonky/commit/b4956c6be76012dde29eaffb7266a10955405991

It'd be great if we could introduce this to the setup tool as well.
RoboZonky 6.2.0 with support for this will be released in a couple of days, but there is no real dependency there - take your time.

**Comment by jhrcek** [comment]
Ok, will take a look over the weekend. Should be fairly straightforward change.
