### ISSUE TITLE
New sell strategy conditions for remaining interest

### ISSUE THREAD

**Issue by triceo** [RoboZonky/natural-strategy-setup#80]
Due to popular demand, I have added some new sale conditions to the strategy:
https://github.com/RoboZonky/robozonky/commit/3367b4f667aae367d66ba1f95ea0e45db1fdf623

It'd be great if you could find the time to implement those in the tool, @jhrcek. RoboZonky 6.3.0 will be released most likely during the weekend of January 23rd.

**Comment by jhrcek** [comment]
Sure, I'll implement it tomorrow. But can you confirm what are the valid value ranges that I should allow for both?
The percent one: 0-100 or 1-100 including/excluding bounds?
The absolute one: is any positive Kč value ok?

**Comment by triceo** [comment]
> The percent one: 0-100 or 1-100 including/excluding bounds?

From the logic of things, 0-100. If we want to be extra smart, "přesahuje 0" or is always true, therefore needn't be offered. But let's not complicate things, do just 0-100.

> The absolute one: is any positive Kč value ok?

Yes. I don't know of a fool-proof formula to figure out maximum possible total interest on the biggest possible loan.

> Also which [condition category](https://github.com/RoboZonky/natural-strategy-setup/blob/373be51827e4d3651d23da66e39dec01e4d31d08/src/Data/Filter/Conditions.elm#L710-L776) would you add them to? I'd go for "Splácení"..

Makes sense.

**Comment by triceo** [comment]
On the other hand, please hold of for a moment. During testing of CR1, we have identified a problem with one of the conditions and it may have to be removed altogether as it can not be implemented consistently. 

I'll let you know when we reach some sort of a conclusion.

**Comment by triceo** [comment]
OK, I reverted the changes, there is nothing to be done here. 
Sorry for the disruption.
