### ISSUE TITLE
Chyba při obnově strategie z URL

### ISSUE THREAD

**Issue by archenroot** [RoboZonky/natural-strategy-setup#83]
Při pokusu obnovit strategii z URL https://robozonky.github.io/konfigurace-strategie/#Njt7ImgiOnsiYSI6MiwiYiI6WyIwIl0sImMiOlsxXSwiZCI6NDAwMCwiZDEiOjE0MDAsImcxIjowfSwiaiI6WzQwMDAsNDAwMCw0MDAwLDQwMDAsNDAwMCw0MDAwLDQwMDAsNDAwMCw0MDAwLDQwMDAsNDAwMF0sImoxIjpbMTQwMCwxNDAwLDE0MD

 došlo k chybě: Problem with the given value:

"{\"h\":{\"a\":2,\"b\":[\"0\"],\"c\":[1],\"d\":4000,\"d1\":1400,\"g1\":0},\"j\":[4000,4000,4000,4000,4000,4000,4000,4000,4000,4000,4000],\"j1\":[1400,1400,140"

This is not valid JSON! Unexpected end of JSON input

**Comment by jhrcek** [comment]
Díky za nahlášení chyby.
Problém je jasný: URL, ze kterého strategii obnovujete je neúplné (tipl bych na chybu při kopírování url ze strategie - pravděpodobně jste nevybral(a) celé URL - chybí nějaké znaky na konci).
Můžete, prosím přiložit soubor strategie, kterou se snažíte obnovit?
Případně část konfiguračního souboru `robozonky-strategy.cfg`, která se nachází pod "-------------------------------------------------------------------"?

**Comment by jhrcek** [comment]
Zavírám pro nedostatek informací.

**Comment by jhrcek** [comment]
Zavírám pro nedostatek informací.
